# Generated by Django 3.0.3 on 2020-10-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drumkits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('library', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
            ],
        ),
    ]
